"""add semantic_types trigger_templates unit_conversions direction

Revision ID: 33f9a504cc1d
Revises: b876f187b765
Create Date: 2026-03-29 23:59:01.022685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f9a504cc1d'
down_revision: Union[str, Sequence[str], None] = 'b876f187b765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trigger_templates_semantic_type_id'), 'trigger_templates', ['semantic_type_id'], unique=False)
    op.create_index(op.f('ix_unit_conversions_semantic_type_id'), 'unit_conversions', ['semantic_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_conversions_semantic_type_id'), table_name='unit_conversions')
    op.drop_index(op.f('ix_trigger_templates_semantic_type_id'), table_name='trigger_templates')
    # ### end Alembic commands ###
