"""add firmware_version and capabilities to devices

Revision ID: 4c91c4d560b4
Revises: 1d2f5dd8af75
Create Date: 2025-12-18 03:11:48.174353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c91c4d560b4'
down_revision: Union[str, Sequence[str], None] = '1d2f5dd8af75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('firmware_version', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('capabilities', sa.JSON(), nullable=True))
    op.drop_column('devices', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('devices', 'capabilities')
    op.drop_column('devices', 'firmware_version')
    # ### end Alembic commands ###
