"""add device identity fields

Revision ID: 5348f7cbe876
Revises: 33f9a504cc1d
Create Date: 2026-03-30 00:30:14.524098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5348f7cbe876'
down_revision: Union[str, Sequence[str], None] = '33f9a504cc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'reporting_interval_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('reporting_interval_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
