"""add automation_rules and automation_fire_log

Revision ID: b876f187b765
Revises: c2d3e4f5g6h7
Create Date: 2026-03-28 12:56:18.776809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b876f187b765'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5g6h7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), server_default='300', nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fire_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_org_id'), 'automation_rules', ['org_id'], unique=False)
    op.create_table('automation_fire_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_fire_log_rule_id'), 'automation_fire_log', ['rule_id'], unique=False)
    op.drop_index(op.f('ix_config_v1_namespace_key'), table_name='config_v1')
    op.drop_constraint(op.f('uq_config_v1_namespace_key'), 'config_v1', type_='unique')
    op.create_index(op.f('ix_config_v1_key'), 'config_v1', ['key'], unique=False)
    op.drop_index(op.f('uq_device_tokens_active_device_id'), table_name='device_tokens', postgresql_where='(is_active = true)')
    op.drop_column('devices', 'reporting_interval_seconds')
    op.drop_index(op.f('ix_effects_v1_created_at'), table_name='effects_v1')
    op.drop_constraint(op.f('uq_effects_v1_effect_id'), 'effects_v1', type_='unique')
    op.create_index(op.f('ix_effects_v1_effect_id'), 'effects_v1', ['effect_id'], unique=True)
    op.drop_constraint(op.f('uq_firmware_versions_version'), 'firmware_versions', type_='unique')
    op.drop_index(op.f('ix_firmware_versions_version'), table_name='firmware_versions')
    op.create_index(op.f('ix_firmware_versions_version'), 'firmware_versions', ['version'], unique=True)
    op.drop_constraint(op.f('uq_organizations_slug'), 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_constraint(op.f('uq_pairing_sessions_device_uid_pairing_code'), 'pairing_sessions', type_='unique')
    op.drop_constraint(op.f('uq_pairing_sessions_pairing_code'), 'pairing_sessions', type_='unique')
    op.drop_index(op.f('ix_pairing_sessions_pairing_code'), table_name='pairing_sessions')
    op.create_index(op.f('ix_pairing_sessions_pairing_code'), 'pairing_sessions', ['pairing_code'], unique=True)
    op.drop_constraint(op.f('uq_secrets_v1_namespace_key'), 'secrets_v1', type_='unique')
    op.drop_index(op.f('ix_signals_v1_stream_id'), table_name='signals_v1')
    op.drop_index(op.f('uq_tasks_client_idempotency'), table_name='tasks', postgresql_where='(idempotency_key IS NOT NULL)')
    op.alter_column('variable_definitions', 'enum_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('variable_effects', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('variable_effects', 'error',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('variable_snapshot_items', 'value_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('variable_snapshot_items', 'constraints',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('uq_variable_values_global_key'), table_name='variable_values', postgresql_where="((device_id IS NULL) AND ((scope)::text = 'global'::text))")
    op.create_foreign_key(None, 'variable_values', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variable_values', type_='foreignkey')
    op.create_index(op.f('uq_variable_values_global_key'), 'variable_values', ['variable_key'], unique=True, postgresql_where="((device_id IS NULL) AND ((scope)::text = 'global'::text))")
    op.alter_column('variable_snapshot_items', 'constraints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('variable_snapshot_items', 'value_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('variable_effects', 'error',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('variable_effects', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('variable_definitions', 'enum_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('uq_tasks_client_idempotency'), 'tasks', ['client_id', 'idempotency_key'], unique=True, postgresql_where='(idempotency_key IS NOT NULL)')
    op.create_index(op.f('ix_signals_v1_stream_id'), 'signals_v1', ['stream', 'id'], unique=False)
    op.create_unique_constraint(op.f('uq_secrets_v1_namespace_key'), 'secrets_v1', ['namespace', 'key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pairing_sessions_pairing_code'), table_name='pairing_sessions')
    op.create_index(op.f('ix_pairing_sessions_pairing_code'), 'pairing_sessions', ['pairing_code'], unique=False)
    op.create_unique_constraint(op.f('uq_pairing_sessions_pairing_code'), 'pairing_sessions', ['pairing_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_pairing_sessions_device_uid_pairing_code'), 'pairing_sessions', ['device_uid', 'pairing_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_organizations_slug'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_firmware_versions_version'), table_name='firmware_versions')
    op.create_index(op.f('ix_firmware_versions_version'), 'firmware_versions', ['version'], unique=False)
    op.create_unique_constraint(op.f('uq_firmware_versions_version'), 'firmware_versions', ['version'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_effects_v1_effect_id'), table_name='effects_v1')
    op.create_unique_constraint(op.f('uq_effects_v1_effect_id'), 'effects_v1', ['effect_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_effects_v1_created_at'), 'effects_v1', ['created_at'], unique=False)
    op.add_column('devices', sa.Column('reporting_interval_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_device_tokens_active_device_id'), 'device_tokens', ['device_id'], unique=True, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_config_v1_key'), table_name='config_v1')
    op.create_unique_constraint(op.f('uq_config_v1_namespace_key'), 'config_v1', ['namespace', 'key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_config_v1_namespace_key'), 'config_v1', ['namespace', 'key'], unique=False)
    op.drop_index(op.f('ix_automation_fire_log_rule_id'), table_name='automation_fire_log')
    op.drop_table('automation_fire_log')
    op.drop_index(op.f('ix_automation_rules_org_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
