import logging
import os
from typing import Iterable

from app.core.config import settings

logger = logging.getLogger("uvicorn.error")

# Central registry (single source of truth). Append-only.
CAPABILITY_REGISTRY: set[str] = {
    "cap.admin",
    "config.write",
    "config.read",
    "secrets.write",
    "secrets.read",
    "audit.read",
    "audit.write",
    "mic.admin",
    "vars.read",
    "vars.write",
    "vars.ack",
    "devices.read",
    "devices.write",
    "devices.token.reissue",
    "devices.unclaim",
    "devices.purge",
    "pairing.start",
    "pairing.claim",
    "pairing.confirm",
    "pairing.status",
    "modules.read",
    "modules.write",
    "devices.hello",
    "telemetry.emit",
    "telemetry.read",
    "tasks.read",
    "tasks.write",
    "users.read",
    "core.auth.login",
    "core.auth.register",
    "entities.read",
    "events.read",
    "events.emit",
    "events.ack",
    "effects.read",
    "providers.read",
    "providers.write",
    "signals.read",
    "signals.ingest",
    "executions.read",
    "executions.write",
    "webhooks.read",
    "webhooks.write",
    "entities.write",
    "groups.read",
    "groups.write",
    "alerts.read",
    "alerts.write",
    "metrics.read",
    "org.read",
    "org.write",
    "org.admin",
    "org.members.read",
    "org.members.write",
}

# Route -> capability mapping (method, path_template)
CAPABILITY_MAP: dict[tuple[str, str], list[str]] = {
    ("POST", "/api/v1/auth/register"): ["core.auth.register"],
    ("POST", "/api/v1/auth/login"): ["core.auth.login"],
    ("GET", "/api/v1/users/me"): ["users.read"],
    ("POST", "/api/v1/devices/hello"): ["devices.hello"],
    ("GET", "/api/v1/devices/whoami"): ["devices.read"],
    ("GET", "/api/v1/devices/lookup/{device_uid}"): ["devices.read"],
    ("GET", "/api/v1/devices"): ["devices.read"],
    ("GET", "/api/v1/devices/{device_id}"): ["devices.read"],
    ("GET", "/api/v1/devices/{device_id}/telemetry/recent"): ["telemetry.read"],
    ("GET", "/api/v1/devices/{device_id}/telemetry"): ["telemetry.read"],
    ("POST", "/api/v1/devices/{device_id}/tasks"): ["tasks.write"],
    ("GET", "/api/v1/devices/{device_id}/tasks"): ["tasks.read"],
    ("GET", "/api/v1/devices/{device_id}/current-task"): ["tasks.read"],
    ("GET", "/api/v1/devices/{device_id}/task-history"): ["tasks.read"],
    ("POST", "/api/v1/devices/{device_id}/tasks/{task_id}/cancel"): ["tasks.write"],
    ("POST", "/api/v1/devices/{device_id}/token/reissue"): ["devices.token.reissue"],
    ("POST", "/api/v1/devices/{device_id}/unclaim"): ["devices.unclaim"],
    ("POST", "/api/v1/devices/{device_id}/purge"): ["devices.purge"],
    ("POST", "/api/v1/devices/purge"): ["devices.purge"],
    ("POST", "/api/v1/devices/purge-bulk"): ["devices.purge"],
    ("POST", "/api/v1/devices/pairing/hello"): ["pairing.start"],
    ("POST", "/api/v1/pairing/hello"): ["pairing.start"],
    ("POST", "/api/v1/pairing/start"): ["pairing.start"],
    ("POST", "/api/v1/pairing/claim"): ["pairing.claim"],
    ("POST", "/api/v1/pairing/confirm"): ["pairing.confirm"],
    ("GET", "/api/v1/pairing/status"): ["pairing.status"],
    ("POST", "/api/v1/devices/pairing/start"): ["pairing.start"],
    ("POST", "/api/v1/devices/pairing/claim"): ["pairing.claim"],
    ("POST", "/api/v1/devices/pairing/confirm"): ["pairing.confirm"],
    ("GET", "/api/v1/devices/pairing/status"): ["pairing.status"],
    ("GET", "/api/v1/modules"): ["modules.read"],
    ("GET", "/api/v1/modules/{key}"): ["modules.read"],
    ("POST", "/api/v1/modules/{key}/enable"): ["modules.write"],
    ("POST", "/api/v1/modules/{key}/disable"): ["modules.write"],
    ("POST", "/api/v1/telemetry"): ["telemetry.emit"],
    ("GET", "/api/v1/telemetry/recent"): ["telemetry.read"],
    ("POST", "/api/v1/tasks/context/heartbeat"): ["tasks.write"],
    ("POST", "/api/v1/tasks/poll"): ["tasks.read"],
    ("POST", "/api/v1/tasks/{task_id}/complete"): ["tasks.write"],
    ("POST", "/api/v1/tasks/{task_id}/renew"): ["tasks.write"],
    ("GET", "/api/v1/variables/definitions"): ["vars.read"],
    ("GET", "/api/v1/variables/defs"): ["vars.read"],
    ("POST", "/api/v1/variables/definitions"): ["vars.write"],
    ("POST", "/api/v1/variables/defs"): ["vars.write"],
    ("GET", "/api/v1/variables/value"): ["vars.read"],
    ("PUT", "/api/v1/variables/value"): ["vars.write"],
    ("POST", "/api/v1/variables/set"): ["vars.write"],
    ("GET", "/api/v1/variables/device/{device_uid}"): ["vars.read"],
    ("GET", "/api/v1/variables/effective"): ["vars.read"],
    ("GET", "/api/v1/variables/snapshot"): ["vars.read"],
    ("POST", "/api/v1/variables/applied"): ["vars.ack"],
    ("POST", "/api/v1/variables/ack"): ["vars.ack"],
    ("GET", "/api/v1/variables/applied"): ["vars.read"],
    ("GET", "/api/v1/variables/audit"): ["vars.read"],
    ("GET", "/api/v1/variables/effects"): ["vars.read"],
    ("GET", "/api/v1/variables/effects/{effect_id}"): ["vars.read"],
    ("POST", "/api/v1/variables/effects/run-once"): ["vars.write"],
    ("GET", "/api/v1/entities"): ["entities.read"],
    ("GET", "/api/v1/entities/{entity_id}"): ["entities.read"],
    ("GET", "/api/v1/entities/{entity_id}/devices"): ["entities.read"],
    ("GET", "/api/v1/events"): ["events.read"],
    ("GET", "/api/v1/events/{event_id}"): ["events.read"],
    ("POST", "/api/v1/events/ack"): ["events.ack"],
    ("POST", "/api/v1/events/emit"): ["events.emit"],
    ("GET", "/api/v1/audit"): ["audit.read"],
    ("GET", "/api/v1/audit/{entry_id}"): ["audit.read"],
    ("GET", "/api/v1/secrets"): ["secrets.read"],
    ("GET", "/api/v1/secrets/{secret_id}"): ["secrets.read"],
    ("GET", "/api/v1/config"): ["config.read"],
    ("GET", "/api/v1/config/{config_id}"): ["config.read"],
    ("GET", "/api/v1/effects"): ["effects.read"],
    ("GET", "/api/v1/effects/{effect_id}"): ["effects.read"],
    ("GET", "/api/v1/signals"): ["signals.read"],
    ("GET", "/api/v1/executions/runs"): ["executions.read"],
    ("POST", "/api/v1/executions/definitions"): ["executions.write"],
    ("POST", "/api/v1/executions/runs"): ["executions.write"],
    ("POST", "/api/v1/executions/runs/{run_id}/finalize"): ["executions.write"],
    ("POST", "/api/v1/executions/runs/{run_id}/claim"): ["executions.write"],
    ("POST", "/api/v1/executions/runs/{run_id}/lease"): ["executions.write"],
    ("POST", "/api/v1/executions/runs/{run_id}/release"): ["executions.write"],
    ("POST", "/api/v1/executions/runs/claim-next"): ["executions.write"],
    ("POST", "/api/v1/executions/workers/heartbeat"): ["executions.write"],
    ("POST", "/api/v1/executions/workers/{worker_id}/definitions"): ["executions.write"],
    ("GET", "/api/v1/executions/workers"): ["executions.read"],
    ("GET", "/api/v1/executions/workers/{worker_id}/definitions"): ["executions.read"],
    ("GET", "/api/v1/executions/definitions/{definition_key}/workers"): ["executions.read"],
    ("GET", "/api/v1/executions/definitions"): ["executions.read"],
    ("GET", "/api/v1/executions/runs/{run_id}"): ["executions.read"],
    ("GET", "/api/v1/executions/definitions/{definition_key}"): ["executions.read"],
    ("POST", "/api/v1/webhooks"): ["webhooks.write"],
    ("GET", "/api/v1/webhooks"): ["webhooks.read"],
    ("GET", "/api/v1/webhooks/{webhook_id}"): ["webhooks.read"],
    ("DELETE", "/api/v1/webhooks/{webhook_id}"): ["webhooks.write"],
    ("POST", "/api/v1/entities"): ["entities.write"],
    ("PUT", "/api/v1/entities/{entity_id}"): ["entities.write"],
    ("DELETE", "/api/v1/entities/{entity_id}"): ["entities.write"],
    ("POST", "/api/v1/entities/{entity_id}/devices"): ["entities.write"],
    ("DELETE", "/api/v1/entities/{entity_id}/devices/{device_id}"): ["entities.write"],
    ("PUT", "/api/v1/entities/{entity_id}/devices/{device_id}"): ["entities.write"],
    ("POST", "/api/v1/entities/{entity_id}/devices/bulk-bind"): ["entities.write"],
    ("POST", "/api/v1/entities/{entity_id}/devices/bulk-unbind"): ["entities.write"],
    ("GET", "/api/v1/entities/{entity_id}/health"): ["entities.read"],
    ("GET", "/api/v1/groups"): ["groups.read"],
    ("POST", "/api/v1/groups"): ["groups.write"],
    ("GET", "/api/v1/groups/{group_id}/devices"): ["groups.read"],
    ("POST", "/api/v1/alerts/rules"): ["alerts.write"],
    ("GET", "/api/v1/alerts/rules"): ["alerts.read"],
    ("GET", "/api/v1/alerts/rules/{rule_id}"): ["alerts.read"],
    ("PUT", "/api/v1/alerts/rules/{rule_id}"): ["alerts.write"],
    ("DELETE", "/api/v1/alerts/rules/{rule_id}"): ["alerts.write"],
    ("GET", "/api/v1/alerts"): ["alerts.read"],
    ("GET", "/api/v1/alerts/{event_id}"): ["alerts.read"],
    ("POST", "/api/v1/alerts/{event_id}/ack"): ["alerts.write"],
    ("POST", "/api/v1/alerts/{event_id}/resolve"): ["alerts.write"],
    ("GET", "/api/v1/metrics"): ["metrics.read"],
    ("POST", "/api/v1/auth/switch-org"): ["core.auth.login"],
    ("POST", "/api/v1/orgs"): ["org.write"],
    ("GET", "/api/v1/orgs"): ["org.read"],
    ("GET", "/api/v1/orgs/{org_id}"): ["org.read"],
    ("PUT", "/api/v1/orgs/{org_id}"): ["org.write"],
    ("DELETE", "/api/v1/orgs/{org_id}"): ["org.admin"],
    ("GET", "/api/v1/orgs/{org_id}/members"): ["org.members.read"],
    ("POST", "/api/v1/orgs/{org_id}/members"): ["org.members.write"],
    ("PUT", "/api/v1/orgs/{org_id}/members/{target_user_id}"): ["org.members.write"],
    ("DELETE", "/api/v1/orgs/{org_id}/members/{target_user_id}"): ["org.members.write"],
}

# Public whitelist (auth-free, minimal, static).
PUBLIC_WHITELIST: set[tuple[str, str]] = {
    ("POST", "/api/v1/auth/register"),
    ("POST", "/api/v1/auth/login"),
    ("POST", "/api/v1/devices/hello"),
    ("POST", "/api/v1/devices/pairing/hello"),
    ("POST", "/api/v1/pairing/hello"),
    ("POST", "/api/v1/pairing/confirm"),
    ("POST", "/api/v1/devices/pairing/confirm"),
    ("GET", "/api/v1/pairing/status"),
    ("GET", "/api/v1/devices/pairing/status"),
}

def enforcement_enabled() -> bool:
    # Env override takes precedence (for tests), otherwise use settings.
    env = os.getenv("HUBEX_CAPS_ENFORCE")
    if env is not None:
        return env == "1"
    return settings.caps_enforce

def validate_caps(caps: Iterable[str]) -> list[str]:
    unknown = [cap for cap in caps if cap not in CAPABILITY_REGISTRY]
    return unknown

def resolve_required_caps(method: str, path: str) -> list[str] | None:
    return CAPABILITY_MAP.get((method.upper(), path))

def is_public_route(method: str, path: str) -> bool:
    return (method.upper(), path) in PUBLIC_WHITELIST
