"""Firmware code templates for HubEx device types.

Used by the Code Generator to produce deployment-ready projects for:
    - PlatformIO  (src/main.cpp + platformio.ini)
    - Arduino IDE (flat .ino sketch)
    - MicroPython (main.py + boot.py)

Templates use `str.format()` style placeholders (``{name}``), NOT Jinja2.
Literal curly braces must be doubled (``{{`` / ``}}``).
"""

ESP32_BRIDGE_TEMPLATE = '''
// HubEx ESP32 Bridge Firmware
// Auto-generated by HubEx — DO NOT EDIT MANUALLY
// Board: {board_name} | Target: {target_board}

#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>

// ── Configuration ──
const char* WIFI_SSID = "{wifi_ssid}";
const char* WIFI_PASS = "{wifi_pass}";
const char* HUBEX_SERVER = "{server_url}";
const char* DEVICE_TOKEN = "{device_token}";
const int BAUD_RATE = {baud_rate};
const int TELEMETRY_INTERVAL = {telemetry_interval} * 1000;

// ── State ──
unsigned long lastTelemetry = 0;
unsigned long lastHeartbeat = 0;
String serialBuffer = "";

void setup() {{
  Serial.begin(BAUD_RATE);   // Bridge serial
  Serial2.begin(115200);     // Debug serial (optional)

  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {{
    delay(500);
  }}
}}

void loop() {{
  // Read from Arduino
  while (Serial.available()) {{
    char c = Serial.read();
    if (c == '\\n') {{
      processMessage(serialBuffer);
      serialBuffer = "";
    }} else {{
      serialBuffer += c;
    }}
  }}

  // Periodic telemetry push
  if (millis() - lastTelemetry > TELEMETRY_INTERVAL) {{
    pushTelemetry();
    lastTelemetry = millis();
  }}

  // Heartbeat
  if (millis() - lastHeartbeat > 30000) {{
    Serial.println("PING");
    sendHeartbeat();
    lastHeartbeat = millis();
  }}
}}

void processMessage(String msg) {{
  if (msg.startsWith("VAR ")) {{
    // Parse: VAR key value
    int sp = msg.indexOf(' ', 4);
    String key = msg.substring(4, sp);
    String val = msg.substring(sp + 1);
    storeVariable(key, val);
  }}
  else if (msg.startsWith("PONG")) {{
    // Arduino alive
  }}
  else if (msg.startsWith("ACK ")) {{
    // Command acknowledged
  }}
  else if (msg.startsWith("META ")) {{
    // Device metadata
  }}
}}

// Placeholder functions — filled by code generator
void storeVariable(String key, String value) {{}}
void pushTelemetry() {{}}
void sendHeartbeat() {{}}
'''

ARDUINO_CLIENT_TEMPLATE = '''
// HubEx Arduino Client (Bridge Mode)
// Auto-generated by HubEx — communicates with ESP32 Bridge via Serial
// Target: {board_name}

{library_includes}

// ── Pin Configuration ──
{pin_defines}

// ── Sensor Setup ──
{sensor_init}

void setup() {{
  Serial.begin({baud_rate});
  {pin_setup}
  {sensor_setup}

  Serial.println("RDY");
  Serial.println("META name \\"{device_name}\\"");
  Serial.println("META version \\"1.0.0\\"");
}}

void loop() {{
  // Check for incoming commands from ESP
  if (Serial.available()) {{
    String cmd = Serial.readStringUntil('\\n');
    processCommand(cmd);
  }}

  // Read sensors and report
  {sensor_read}

  delay({read_interval});
}}

void processCommand(String cmd) {{
  if (cmd.startsWith("SET ")) {{
    int sp = cmd.indexOf(' ', 4);
    String key = cmd.substring(4, sp);
    String val = cmd.substring(sp + 1);
    handleSet(key, val);
  }}
  else if (cmd == "PING") {{
    Serial.println("PONG");
  }}
}}

void handleSet(String key, String value) {{
  {actuator_handlers}
  Serial.print("ACK SET ");
  Serial.println(key);
}}
'''

DIRECT_ESP32_TEMPLATE = '''
// HubEx Direct ESP32 Device
// Auto-generated by HubEx — connects directly to HubEx via WiFi
// Board: {board_name}

#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>

{library_includes}

const char* WIFI_SSID = "{wifi_ssid}";
const char* WIFI_PASS = "{wifi_pass}";
const char* HUBEX_SERVER = "{server_url}";
const char* DEVICE_TOKEN = "{device_token}";

{pin_defines}
{sensor_init}

void setup() {{
  Serial.begin(115200);
  {pin_setup}
  {sensor_setup}

  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {{ delay(500); }}
  Serial.println("Connected to WiFi");
}}

void loop() {{
  {sensor_read}

  // Send telemetry
  if (WiFi.status() == WL_CONNECTED) {{
    HTTPClient http;
    http.begin(String(HUBEX_SERVER) + "/api/v1/telemetry");
    http.addHeader("X-Device-Token", DEVICE_TOKEN);
    http.addHeader("Content-Type", "application/json");

    JsonDocument doc;
    doc["event_type"] = "sensor_reading";
    JsonObject payload = doc["payload"].to<JsonObject>();
    {telemetry_fields}

    String json;
    serializeJson(doc, json);
    http.POST(json);
    http.end();
  }}

  delay({read_interval});
}}
'''


# =============================================================================
# Sprint 2: Project-ZIP templates (PlatformIO, Arduino IDE, MicroPython, README)
# =============================================================================

# ---- PlatformIO ---------------------------------------------------------

PLATFORMIO_INI_TEMPLATE = '''; HubEx — PlatformIO Project Configuration
; Auto-generated — safe to edit, but `lib_deps` and `board` must stay correct.
; Full docs: https://docs.platformio.org/page/projectconf.html

[env:{env_name}]
platform = {platform}
board = {pio_board}
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Build flags — exposes the WiFi/API-key constants from include/config.h
build_flags =
    -Iinclude
    -D HUBEX_DEVICE=\\"{device_name}\\"

; Arduino libraries needed by the selected components
lib_deps =
{lib_deps}
'''


PLATFORMIO_MAIN_CPP_TEMPLATE = '''// HubEx — Device Firmware (PlatformIO / Arduino framework)
// Board: {board_name}
// Auto-generated — safe to edit.

#include <Arduino.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>
#include "config.h"

{library_includes}

{pin_defines}
{sensor_init}

const unsigned long READ_INTERVAL_MS = {read_interval};
unsigned long lastRead = 0;

void connectWifi() {{
  Serial.print("[HUBEX] Connecting to ");
  Serial.println(HUBEX_WIFI_SSID);
  WiFi.begin(HUBEX_WIFI_SSID, HUBEX_WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {{
    delay(500);
    Serial.print(".");
  }}
  Serial.println();
  Serial.print("[HUBEX] WiFi OK, ip=");
  Serial.println(WiFi.localIP());
}}

void pushTelemetry() {{
  if (WiFi.status() != WL_CONNECTED) {{
    connectWifi();
  }}
  HTTPClient http;
  http.begin(String(HUBEX_SERVER_URL) + "/api/v1/telemetry");
  http.addHeader("X-Device-Token", HUBEX_DEVICE_TOKEN);
  http.addHeader("Content-Type", "application/json");

  JsonDocument doc;
  doc["event_type"] = "sensor_reading";
  JsonObject payload = doc["payload"].to<JsonObject>();
{telemetry_fields}

  String json;
  serializeJson(doc, json);
  int code = http.POST(json);
  Serial.printf("[HUBEX] telemetry -> %d\\n", code);
  http.end();
}}

void setup() {{
  Serial.begin(115200);
  delay(200);
  Serial.println("[HUBEX] Booting " HUBEX_DEVICE);

  {pin_setup}
  {sensor_setup}

  connectWifi();
}}

void loop() {{
  if (millis() - lastRead >= READ_INTERVAL_MS) {{
    lastRead = millis();
{sensor_read}
    pushTelemetry();
  }}
  delay(10);
}}
'''


# ---- Arduino IDE --------------------------------------------------------

ARDUINO_IDE_INO_TEMPLATE = '''// HubEx — Device Firmware (Arduino IDE flat sketch)
// Board: {board_name}
// Auto-generated by HubEx Code Generator.
//
// REQUIRED LIBRARIES (install via Arduino IDE > Tools > Manage Libraries):
{arduino_lib_comment}

#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>
#include "config.h"

{library_includes}

{pin_defines}
{sensor_init}

const unsigned long READ_INTERVAL_MS = {read_interval};
unsigned long lastRead = 0;

void connectWifi() {{
  WiFi.begin(HUBEX_WIFI_SSID, HUBEX_WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {{
    delay(500);
  }}
}}

void pushTelemetry() {{
  if (WiFi.status() != WL_CONNECTED) {{ connectWifi(); }}
  HTTPClient http;
  http.begin(String(HUBEX_SERVER_URL) + "/api/v1/telemetry");
  http.addHeader("X-Device-Token", HUBEX_DEVICE_TOKEN);
  http.addHeader("Content-Type", "application/json");

  JsonDocument doc;
  doc["event_type"] = "sensor_reading";
  JsonObject payload = doc["payload"].to<JsonObject>();
{telemetry_fields}

  String json;
  serializeJson(doc, json);
  http.POST(json);
  http.end();
}}

void setup() {{
  Serial.begin(115200);
  {pin_setup}
  {sensor_setup}
  connectWifi();
}}

void loop() {{
  if (millis() - lastRead >= READ_INTERVAL_MS) {{
    lastRead = millis();
{sensor_read}
    pushTelemetry();
  }}
  delay(10);
}}
'''


# ---- MicroPython --------------------------------------------------------

MICROPYTHON_BOOT_PY_TEMPLATE = '''# HubEx — boot.py (runs once on device boot)
# Connects to WiFi so main.py can push telemetry.

import network
import time
from config import WIFI_SSID, WIFI_PASS

def _connect():
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    if not wlan.isconnected():
        print("[HUBEX] connecting to", WIFI_SSID)
        wlan.connect(WIFI_SSID, WIFI_PASS)
        for _ in range(30):
            if wlan.isconnected():
                break
            time.sleep(0.5)
    if wlan.isconnected():
        print("[HUBEX] wifi ok:", wlan.ifconfig())
    else:
        print("[HUBEX] wifi FAILED")

_connect()
'''


MICROPYTHON_MAIN_PY_TEMPLATE = '''# HubEx — main.py (MicroPython firmware)
# Board: {board_name}
# Auto-generated by HubEx Code Generator.

import time
try:
    import urequests as requests
except ImportError:
    import requests

from machine import Pin
from config import SERVER_URL, DEVICE_TOKEN

{mpy_imports}

READ_INTERVAL_S = {read_interval_s}

# ── Pin setup ──────────────────────────────────────────────────────────
{mpy_pin_setup}

# ── Sensor init ────────────────────────────────────────────────────────
{mpy_sensor_init}


def read_sensors():
    """Return a dict of variable_key -> value."""
    payload = {{}}
{mpy_sensor_read}
    return payload


def push_telemetry(payload):
    try:
        r = requests.post(
            SERVER_URL + "/api/v1/telemetry",
            headers={{
                "X-Device-Token": DEVICE_TOKEN,
                "Content-Type": "application/json",
            }},
            json={{"event_type": "sensor_reading", "payload": payload}},
        )
        print("[HUBEX] telemetry ->", r.status_code)
        r.close()
    except Exception as e:
        print("[HUBEX] telemetry error:", e)


print("[HUBEX] main loop started")
while True:
    push_telemetry(read_sensors())
    time.sleep(READ_INTERVAL_S)
'''


MICROPYTHON_CONFIG_PY_TEMPLATE = '''# HubEx — Device configuration
# Auto-generated. Safe to edit WiFi + SERVER_URL later.

WIFI_SSID = "{wifi_ssid}"
WIFI_PASS = "{wifi_pass}"
SERVER_URL = "{server_url}"
DEVICE_TOKEN = "{device_token}"
DEVICE_NAME = "{device_name}"
'''


# ---- Shared: config.h for C++ projects + README + .gitignore -------------

CONFIG_H_TEMPLATE = '''// HubEx — Device configuration header
// Auto-generated. Safe to edit the WiFi + server URL later.

#ifndef HUBEX_CONFIG_H
#define HUBEX_CONFIG_H

#define HUBEX_WIFI_SSID     "{wifi_ssid}"
#define HUBEX_WIFI_PASS     "{wifi_pass}"
#define HUBEX_SERVER_URL    "{server_url}"
#define HUBEX_DEVICE_TOKEN  "{device_token}"
#define HUBEX_DEVICE_NAME   "{device_name}"

#endif // HUBEX_CONFIG_H
'''


GITIGNORE_TEMPLATE = '''# HubEx auto-generated project
.pio/
.pioenvs/
.piolibdeps/
.vscode/
.idea/
.DS_Store
*.bak
*.swp
'''


README_MD_TEMPLATE = '''# {device_name}

Auto-generated HubEx IoT project for **{board_name}** using the **{framework_label}** framework.

- **Device ID:** `{device_id}`
- **Device Token:** `{device_token_short}\u2026` *(full token is in the config file below)*
- **Components:** {component_list}

## Flashing

{flash_instructions}

## Wiring

| Pin | Component    | Purpose     | Variable       |
| --- | ------------ | ----------- | -------------- |
{wiring_rows}

## WiFi + Server

The firmware uses the credentials baked into `{config_file}`. You can edit them
later — on next boot the device will reconnect with the new values.

- **SSID:** `{wifi_ssid_display}`
- **Server URL:** `{server_url}`

## What happens after flashing

1. The device boots, connects to WiFi, and starts sending telemetry every
   {read_interval_s} seconds to `{server_url}/api/v1/telemetry`.
2. It shows up in your HubEx UI under **Devices** as *{device_name}*.
3. Sensor readings become live **Variables** in the dashboard.

## Re-generate

If you want a different board, different sensors, or a new API key, open the
HubEx UI, go to **Hardware \u2192 Neues ESP-Projekt**, and run the wizard again.

---

*Generated by HubEx Code Generator on {generated_at}*
'''
