"""Firmware code templates for HubEx device types.

Used by the Code Generator (H4) to produce deployment-ready Arduino/ESP sketches.
"""

ESP32_BRIDGE_TEMPLATE = '''
// HubEx ESP32 Bridge Firmware
// Auto-generated by HubEx — DO NOT EDIT MANUALLY
// Board: {board_name} | Target: {target_board}

#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>

// ── Configuration ──
const char* WIFI_SSID = "{wifi_ssid}";
const char* WIFI_PASS = "{wifi_pass}";
const char* HUBEX_SERVER = "{server_url}";
const char* DEVICE_TOKEN = "{device_token}";
const int BAUD_RATE = {baud_rate};
const int TELEMETRY_INTERVAL = {telemetry_interval} * 1000;

// ── State ──
unsigned long lastTelemetry = 0;
unsigned long lastHeartbeat = 0;
String serialBuffer = "";

void setup() {{
  Serial.begin(BAUD_RATE);   // Bridge serial
  Serial2.begin(115200);     // Debug serial (optional)

  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {{
    delay(500);
  }}
}}

void loop() {{
  // Read from Arduino
  while (Serial.available()) {{
    char c = Serial.read();
    if (c == '\\n') {{
      processMessage(serialBuffer);
      serialBuffer = "";
    }} else {{
      serialBuffer += c;
    }}
  }}

  // Periodic telemetry push
  if (millis() - lastTelemetry > TELEMETRY_INTERVAL) {{
    pushTelemetry();
    lastTelemetry = millis();
  }}

  // Heartbeat
  if (millis() - lastHeartbeat > 30000) {{
    Serial.println("PING");
    sendHeartbeat();
    lastHeartbeat = millis();
  }}
}}

void processMessage(String msg) {{
  if (msg.startsWith("VAR ")) {{
    // Parse: VAR key value
    int sp = msg.indexOf(' ', 4);
    String key = msg.substring(4, sp);
    String val = msg.substring(sp + 1);
    storeVariable(key, val);
  }}
  else if (msg.startsWith("PONG")) {{
    // Arduino alive
  }}
  else if (msg.startsWith("ACK ")) {{
    // Command acknowledged
  }}
  else if (msg.startsWith("META ")) {{
    // Device metadata
  }}
}}

// Placeholder functions — filled by code generator
void storeVariable(String key, String value) {{}}
void pushTelemetry() {{}}
void sendHeartbeat() {{}}
'''

ARDUINO_CLIENT_TEMPLATE = '''
// HubEx Arduino Client (Bridge Mode)
// Auto-generated by HubEx — communicates with ESP32 Bridge via Serial
// Target: {board_name}

{library_includes}

// ── Pin Configuration ──
{pin_defines}

// ── Sensor Setup ──
{sensor_init}

void setup() {{
  Serial.begin({baud_rate});
  {pin_setup}
  {sensor_setup}

  Serial.println("RDY");
  Serial.println("META name \\"{device_name}\\"");
  Serial.println("META version \\"1.0.0\\"");
}}

void loop() {{
  // Check for incoming commands from ESP
  if (Serial.available()) {{
    String cmd = Serial.readStringUntil('\\n');
    processCommand(cmd);
  }}

  // Read sensors and report
  {sensor_read}

  delay({read_interval});
}}

void processCommand(String cmd) {{
  if (cmd.startsWith("SET ")) {{
    int sp = cmd.indexOf(' ', 4);
    String key = cmd.substring(4, sp);
    String val = cmd.substring(sp + 1);
    handleSet(key, val);
  }}
  else if (cmd == "PING") {{
    Serial.println("PONG");
  }}
}}

void handleSet(String key, String value) {{
  {actuator_handlers}
  Serial.print("ACK SET ");
  Serial.println(key);
}}
'''

DIRECT_ESP32_TEMPLATE = '''
// HubEx Direct ESP32 Device
// Auto-generated by HubEx — connects directly to HubEx via WiFi
// Board: {board_name}

#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>

{library_includes}

const char* WIFI_SSID = "{wifi_ssid}";
const char* WIFI_PASS = "{wifi_pass}";
const char* HUBEX_SERVER = "{server_url}";
const char* DEVICE_TOKEN = "{device_token}";

{pin_defines}
{sensor_init}

void setup() {{
  Serial.begin(115200);
  {pin_setup}
  {sensor_setup}

  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {{ delay(500); }}
  Serial.println("Connected to WiFi");
}}

void loop() {{
  {sensor_read}

  // Send telemetry
  if (WiFi.status() == WL_CONNECTED) {{
    HTTPClient http;
    http.begin(String(HUBEX_SERVER) + "/api/v1/telemetry");
    http.addHeader("X-Device-Token", DEVICE_TOKEN);
    http.addHeader("Content-Type", "application/json");

    JsonDocument doc;
    doc["event_type"] = "sensor_reading";
    JsonObject payload = doc["payload"].to<JsonObject>();
    {telemetry_fields}

    String json;
    serializeJson(doc, json);
    http.POST(json);
    http.end();
  }}

  delay({read_interval});
}}
'''
